#!/bin/sh
echo "📦 Verificando build de produção do Frontend..."
cd frontend && npm run build || exit 1

echo "📦 Verificando compilação do Backend..."
cd ../backend && npm run build || exit 1

echo "🧪 Executando bateria de testes..."
npm run test || exit 1
